### ISSUE TITLE
Unicode decode error

### ISSUE THREAD

**Issue by jp7carlos** [unu/sublime-ladyphp#1]
First, let me say that i'm a fan of your project. You're changing PHP syntax, without going too far and allowing automatic conversion on Sublime.

Now the Issue: I'm trying to convert a very simple file which has UTF-8 chars, and i get the error:

    Traceback (most recent call last):
	  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 549, in run_
	    return self.run(edit)
	  File "/Users/carlos/Library/Application Support/Sublime Text 3/Packages/sublime-ladyphp/LadyPHP.py", line 63, in run
	    lady.toggle(self.view)
	  File "/Users/carlos/Library/Application Support/Sublime Text 3/Packages/sublime-ladyphp/LadyPHP.py", line 42, in toggle
	    col = min(col, len(new_file.readlines()[row]) - 1)
	  File "./encodings/ascii.py", line 26, in decode
	UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 33: ordinal not in range(128)

My file is:

	<?php

	$teste = 214332432341;

	// Café
	$asda;

Note: My file is saved in UTF-8. When i save it, sublime console says: 
    
    Writing file /Users/carlos/Sites/teste.php with encoding UTF-8 (atomic)

Thx,
Carlos

**Comment by jp7carlos** [comment]
I don't even know python, but it seems to have solved the problem:

Line 41: 
    
    new_file = codecs.open(out, "r", "utf-8")

**Comment by unu** [comment]
Hi @jp7carlos, thank you :). I cannot reproduce the error with Sublime Text 3065. However your fix doesn't seem to break anything, so I will use it.
